

export const OBTENER_PROYECTOS = "OBTENER_PROYECTOS";
export const OBTENER_PROYECTOS_EXITO = "OBTENER_PROYECTOS_EXITO";
export const OBTENER_PROYECTOS_ERROR = "OBTENER_PROYECTOS_ERROR";

export const GUARDAR_PROYECTO = "GUARDAR_PROYECTO";
export const GUARDAR_EXITO = "GUARDAR_EXITO";
export const GUARDAR_ERROR = "GUARDAR_ERROR";